name: CI/CD Workflow for CHIP-8 Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y g++

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install gcc

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install mingw -y
        echo "::add-path::C:\tools\mingw64\bin"

    - name: Compile with g++
      run: |
        g++ -std=c++17 -o chip8_tests chip8.cpp tests/test_chip8.cpp

    - name: Run Tests
      run: ./chip8_tests